version: '3.6'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api_hw
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
    expose:
      - 3306

  app:
    image: api-nbp:latest
    ports:
      - 8080:8080
    depends_on:
      - "db"
    command: sh -c "/wait && /api-nbp"
    environment:
        - WAIT_HOSTS=db:3306
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=30
        - WAIT_HOST_CONNECT_TIMEOUT=30
